#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCompleteTextBox
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="sunil")]
	public partial class AutoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public AutoDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["sunilConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AutoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AutoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AutoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AutoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<NewAdmin> NewAdmins
		{
			get
			{
				return this.GetTable<NewAdmin>();
			}
		}
		
		public System.Data.Linq.Table<InfoBook> InfoBooks
		{
			get
			{
				return this.GetTable<InfoBook>();
			}
		}
		
		public System.Data.Linq.Table<BookImage> BookImages
		{
			get
			{
				return this.GetTable<BookImage>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NewAdmin")]
	public partial class NewAdmin
	{
		
		private string _adminName;
		
		private string _adminPassword;
		
		private int _AdminCode;
		
		private string _AdminPhone;
		
		private string _AdminAddress;
		
		private string _AdminDesignation;
		
		private string _AdminCategory;
		
		private System.DateTime _AdminDate;
		
		private System.Nullable<System.Guid> _UserID;
		
		private int _Active;
		
		public NewAdmin()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adminName", DbType="VarChar(50)")]
		public string adminName
		{
			get
			{
				return this._adminName;
			}
			set
			{
				if ((this._adminName != value))
				{
					this._adminName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adminPassword", DbType="VarChar(50)")]
		public string adminPassword
		{
			get
			{
				return this._adminPassword;
			}
			set
			{
				if ((this._adminPassword != value))
				{
					this._adminPassword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminCode", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int AdminCode
		{
			get
			{
				return this._AdminCode;
			}
			set
			{
				if ((this._AdminCode != value))
				{
					this._AdminCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminPhone", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string AdminPhone
		{
			get
			{
				return this._AdminPhone;
			}
			set
			{
				if ((this._AdminPhone != value))
				{
					this._AdminPhone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminAddress", DbType="VarChar(200)")]
		public string AdminAddress
		{
			get
			{
				return this._AdminAddress;
			}
			set
			{
				if ((this._AdminAddress != value))
				{
					this._AdminAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminDesignation", DbType="VarChar(200)")]
		public string AdminDesignation
		{
			get
			{
				return this._AdminDesignation;
			}
			set
			{
				if ((this._AdminDesignation != value))
				{
					this._AdminDesignation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminCategory", DbType="VarChar(50)")]
		public string AdminCategory
		{
			get
			{
				return this._AdminCategory;
			}
			set
			{
				if ((this._AdminCategory != value))
				{
					this._AdminCategory = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminDate", DbType="SmallDateTime NOT NULL")]
		public System.DateTime AdminDate
		{
			get
			{
				return this._AdminDate;
			}
			set
			{
				if ((this._AdminDate != value))
				{
					this._AdminDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Int NOT NULL")]
		public int Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.InfoBook")]
	public partial class InfoBook
	{
		
		private int _BID;
		
		private string _Book_ID;
		
		private string _BookName;
		
		private string _AuthorName;
		
		private string _Publisher;
		
		private string _Category;
		
		private string _ISBN;
		
		private string _PublishYear;
		
		private System.Nullable<bool> _Available;
		
		private System.Nullable<bool> _Requested;
		
		public InfoBook()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int BID
		{
			get
			{
				return this._BID;
			}
			set
			{
				if ((this._BID != value))
				{
					this._BID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Book_ID", AutoSync=AutoSync.Always, DbType="VarChar(106)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string Book_ID
		{
			get
			{
				return this._Book_ID;
			}
			set
			{
				if ((this._Book_ID != value))
				{
					this._Book_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookName", DbType="NVarChar(100)")]
		public string BookName
		{
			get
			{
				return this._BookName;
			}
			set
			{
				if ((this._BookName != value))
				{
					this._BookName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuthorName", DbType="VarChar(100)")]
		public string AuthorName
		{
			get
			{
				return this._AuthorName;
			}
			set
			{
				if ((this._AuthorName != value))
				{
					this._AuthorName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Publisher", DbType="NVarChar(100)")]
		public string Publisher
		{
			get
			{
				return this._Publisher;
			}
			set
			{
				if ((this._Publisher != value))
				{
					this._Publisher = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="VarChar(100)")]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this._Category = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISBN", DbType="Char(100)")]
		public string ISBN
		{
			get
			{
				return this._ISBN;
			}
			set
			{
				if ((this._ISBN != value))
				{
					this._ISBN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublishYear", DbType="Char(10)")]
		public string PublishYear
		{
			get
			{
				return this._PublishYear;
			}
			set
			{
				if ((this._PublishYear != value))
				{
					this._PublishYear = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Available", DbType="Bit")]
		public System.Nullable<bool> Available
		{
			get
			{
				return this._Available;
			}
			set
			{
				if ((this._Available != value))
				{
					this._Available = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Requested", DbType="Bit")]
		public System.Nullable<bool> Requested
		{
			get
			{
				return this._Requested;
			}
			set
			{
				if ((this._Requested != value))
				{
					this._Requested = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BookImages")]
	public partial class BookImage
	{
		
		private int _Id;
		
		private string _BookID;
		
		private System.Data.Linq.Binary _BookImage1;
		
		private string _Description1;
		
		private string _Description2;
		
		private string _Description3;
		
		private System.Nullable<int> _TotalBooks;
		
		private System.Nullable<decimal> _Price;
		
		public BookImage()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookID", DbType="VarChar(50)")]
		public string BookID
		{
			get
			{
				return this._BookID;
			}
			set
			{
				if ((this._BookID != value))
				{
					this._BookID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="BookImage", Storage="_BookImage1", DbType="Binary(50)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary BookImage1
		{
			get
			{
				return this._BookImage1;
			}
			set
			{
				if ((this._BookImage1 != value))
				{
					this._BookImage1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description1", DbType="NVarChar(2000)")]
		public string Description1
		{
			get
			{
				return this._Description1;
			}
			set
			{
				if ((this._Description1 != value))
				{
					this._Description1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description2", DbType="NVarChar(2000)")]
		public string Description2
		{
			get
			{
				return this._Description2;
			}
			set
			{
				if ((this._Description2 != value))
				{
					this._Description2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description3", DbType="NVarChar(2000)")]
		public string Description3
		{
			get
			{
				return this._Description3;
			}
			set
			{
				if ((this._Description3 != value))
				{
					this._Description3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalBooks", DbType="Int")]
		public System.Nullable<int> TotalBooks
		{
			get
			{
				return this._TotalBooks;
			}
			set
			{
				if ((this._TotalBooks != value))
				{
					this._TotalBooks = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Money")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
